# Generated by Django 3.2.18 on 2023-05-01 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CierreCaja',
        ),
    ]
