# Generated by Django 3.2.18 on 2023-05-01 00:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_delete_cierrecaja'),
    ]

    operations = [
        migrations.CreateModel(
            name='CierreCaja',
            fields=[
                ('numero_reporte', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(default=datetime.datetime.now, unique=True)),
                ('efectivo_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('efectivo_final', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total_ventas', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True)),
                ('gastos', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True)),
                ('pagos_clientes', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True)),
                ('retiros_efectivo', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True)),
                ('final', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True)),
                ('diferencias', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Cierre de Caja',
                'verbose_name_plural': 'Cierres de Caja',
            },
        ),
    ]
