# Generated by Django 3.2.18 on 2023-05-01 00:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_cierrecaja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='fecha_creacion',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
